// Code generated by "stringer -type=MuxSetting"; DO NOT EDIT.

package ads1x15

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mux0_1-0]
	_ = x[Mux0_3-4096]
	_ = x[Mux1_3-8192]
	_ = x[Mux2_3-12288]
	_ = x[Mux0-16384]
	_ = x[Mux1-20480]
	_ = x[Mux2-24576]
	_ = x[Mux3-28672]
}

const (
	_MuxSetting_name_0 = "channel 0-1"
	_MuxSetting_name_1 = "channel 0-3"
	_MuxSetting_name_2 = "channel 1-3"
	_MuxSetting_name_3 = "channel 2-3"
	_MuxSetting_name_4 = "channel 0"
	_MuxSetting_name_5 = "channel 1"
	_MuxSetting_name_6 = "channel 2"
	_MuxSetting_name_7 = "channel 3"
)

func (i MuxSetting) String() string {
	switch {
	case i == 0:
		return _MuxSetting_name_0
	case i == 4096:
		return _MuxSetting_name_1
	case i == 8192:
		return _MuxSetting_name_2
	case i == 12288:
		return _MuxSetting_name_3
	case i == 16384:
		return _MuxSetting_name_4
	case i == 20480:
		return _MuxSetting_name_5
	case i == 24576:
		return _MuxSetting_name_6
	case i == 28672:
		return _MuxSetting_name_7
	default:
		return "MuxSetting(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
